// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoHang_UNETI01_TI17A3HN.Data;

#nullable disable

namespace QuanLyKhoHang_UNETI01_TI17A3HN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930012242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.BoPhanNhan", b =>
                {
                    b.Property<int>("MaBoPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBoPhan"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NguoiDaiDien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenBoPhan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaBoPhan");

                    b.ToTable("BoPhanNhan");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaChiTietNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietNhap"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietNhap");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("MaChiTietXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietXuat"));

                    b.Property<decimal>("DonGiaXuatThamChieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongXuat")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietXuat");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaPhieuXuat");

                    b.ToTable("ChiTietPhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.DonViTinh", b =>
                {
                    b.Property<int>("MaDonViTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonViTinh"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDonViTinh");

                    b.HasIndex("TenDonViTinh")
                        .IsUnique();

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.HangHoa", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<decimal>("GiaNhapThamKhao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiHang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MucTonToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHang");

                    b.HasIndex("MaDonViTinh");

                    b.HasIndex("MaLoaiHang");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.Kho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKho");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.LichSuTonKho", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<string>("MaPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayPhatSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThucHien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TonSauGiaoDich")
                        .HasColumnType("int");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaKho");

                    b.ToTable("LichSuTonKhoes");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.LoaiHang", b =>
                {
                    b.Property<int>("MaLoaiHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHang"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiHang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiHang");

                    b.HasIndex("TenLoaiHang")
                        .IsUnique();

                    b.ToTable("LoaiHang");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiLap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("KhoMaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaBoPhan")
                        .HasColumnType("int");

                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiLap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("KhoMaKho");

                    b.HasIndex("MaBoPhan");

                    b.HasIndex("MaKho");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.TonKho", b =>
                {
                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaKho", "MaHang");

                    b.HasIndex("MaHang");

                    b.ToTable("TonKhoes");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.HangHoa", "HangHoa")
                        .WithMany("DanhSachChiTietNhap")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.HangHoa", "HangHoa")
                        .WithMany("DanhSachChiTietXuat")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.HangHoa", b =>
                {
                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.DonViTinh", "DonViTinh")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.LoaiHang", "LoaiHang")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaLoaiHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.LichSuTonKho", b =>
                {
                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.Kho", "Kho")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.Kho", null)
                        .WithMany("PhieuXuats")
                        .HasForeignKey("KhoMaKho");

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.BoPhanNhan", "BoPhanNhan")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("MaBoPhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoPhanNhan");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.TonKho", b =>
                {
                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.HangHoa", "HangHoa")
                        .WithMany("DanhSachTonKho")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoHang_UNETI01_TI17A3HN.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.BoPhanNhan", b =>
                {
                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.DonViTinh", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.HangHoa", b =>
                {
                    b.Navigation("DanhSachChiTietNhap");

                    b.Navigation("DanhSachChiTietXuat");

                    b.Navigation("DanhSachTonKho");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.Kho", b =>
                {
                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.LoaiHang", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyKhoHang_UNETI01_TI17A3HN.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });
#pragma warning restore 612, 618
        }
    }
}
